# Site settings
title: HT's blog
description: Hello Hello
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "https://rabbitsht.github.io/" # the subpath of your site, e.g. /blog/
url: "https://rabbitsht.github.io/" # the base hostname & protocol for your site
